// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt9I0J9-GcLQDkPR4moJrE94W2HzEZORE',
    appId: '1:99901555407:web:44ef9bb83befa111b8edba',
    messagingSenderId: '99901555407',
    projectId: 'pi4-iot-1b7bb',
    authDomain: 'pi4-iot-1b7bb.firebaseapp.com',
    databaseURL: 'https://pi4-iot-1b7bb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pi4-iot-1b7bb.firebasestorage.app',
    measurementId: 'G-P3YYNT98V5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsn7LA6-5X0nirmhDpnia1rLeflUDe50Y',
    appId: '1:99901555407:android:667315652e67bbd3b8edba',
    messagingSenderId: '99901555407',
    projectId: 'pi4-iot-1b7bb',
    databaseURL: 'https://pi4-iot-1b7bb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pi4-iot-1b7bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6gqjuzEYcyvfmxCuS7iRTFczC7tj57TU',
    appId: '1:99901555407:ios:1c9f9c55f52d9352b8edba',
    messagingSenderId: '99901555407',
    projectId: 'pi4-iot-1b7bb',
    databaseURL: 'https://pi4-iot-1b7bb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pi4-iot-1b7bb.firebasestorage.app',
    iosClientId: '99901555407-63me5na75udo4evj3lv7vigrk192pb9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.appIot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6gqjuzEYcyvfmxCuS7iRTFczC7tj57TU',
    appId: '1:99901555407:ios:1c9f9c55f52d9352b8edba',
    messagingSenderId: '99901555407',
    projectId: 'pi4-iot-1b7bb',
    databaseURL: 'https://pi4-iot-1b7bb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pi4-iot-1b7bb.firebasestorage.app',
    iosClientId: '99901555407-63me5na75udo4evj3lv7vigrk192pb9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.appIot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDt9I0J9-GcLQDkPR4moJrE94W2HzEZORE',
    appId: '1:99901555407:web:2d50c175b8f0f739b8edba',
    messagingSenderId: '99901555407',
    projectId: 'pi4-iot-1b7bb',
    authDomain: 'pi4-iot-1b7bb.firebaseapp.com',
    databaseURL: 'https://pi4-iot-1b7bb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pi4-iot-1b7bb.firebasestorage.app',
    measurementId: 'G-V073RTYW6D',
  );

}